const fullName = 'Nhu Quan (Jimmy) Tran';
const isCool = true;
const totalPets = 0;
console.log('full name: ', fullName);
console.log('type of full name: ', typeof fullName);
console.log('is kool? ', isCool);
console.log('type of isCool: ', typeof isCool);
console.log('total pets: ', totalPets);
console.log('type of totalPets: ', typeof totalPets);
const unknown = null;
console.log('unknown variable: ', unknown);
console.log('type of unknown: ', typeof unknown);
const never = undefined;
console.log('"never" variable: ', never);
console.log('type of never: ', typeof never);
